version: '3.4'
x-var:
  &app_name
    lamp
x-var:
  &default_environment
    - TZ=Asia/Tokyo
    - LANGUAGE=ja_JP.ja
    - LANG=ja_JP.UTF-8
services:
  web:
    image: lamp_web
    build:
      context: .
      dockerfile: DockerFile-web
      args:
        - app_name=*app_name
    container_name: lamp_web
    privileged: true
    command: /sbin/init
    ports:
      - 81:80
      - 3307:3306
      
    environment:
        *default_environment
    volumes:
      - ./volumes/web/docker_initial_files:/docker_initial_files  
      - ./volumes/web/usr/local/bin/web:/usr/local/bin/web
      - ../:/var/www/lamp
      
    networks:
      - lamp_net

networks:
  lamp_net:
    driver: bridge